trigger:
- main

pool:
  name: 'GreenCodeScan'

variables:
  PATH: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\Java\\jdk-21\\bin;C:\\Users\\sansk\\Downloads\\apache-maven-3.9.6\\bin;$PATH'
  PYTHON_PATH: 'C:\\Users\\sansk\\AppData\\Local\\Programs\\Python\\Python312\\python.exe'
  CAST_HIGHLIGHT_PATH: 'C:\\Users\\sansk\\Downloads\\Highlight-Automation-Command'
  PYTEST_PATH: 'C:\\Users\\sansk\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\pytest.exe'
  CLIENT_NAME: 'ZF'

stages:
- stage: CloneRepository
  displayName: 'Stage 1: Clone Repository'
  jobs:
  - job: CloneRepository
    steps:
    - checkout: self
    - script: |
        echo "Client Name: $(CLIENT_NAME)"

- stage: TrackServerEmissions
  displayName: 'Stage 2: Track Server Emissions'
  jobs:
  - job: TrackServerEmissions
    steps:
    - script: |
        cd $(REPO_PATH)
        $(PYTHON_PATH) server_emissions.py
      continueOnError: true

- stage: DynamicCodeAnalysis
  displayName: 'Stage 4: Dynamic Code Analysis'
  jobs:
  - job: DynamicCodeAnalysis
    steps:
    - script: |
        cd $(REPO_PATH)
        $(PYTHON_PATH) track_emissions.py
      continueOnError: true
      env:
        PYTEST: $(PYTEST_PATH)

- stage: UpdateDashboard
  displayName: 'Stage 5: Update Dashboard'
  jobs:
  - job: UpdateDashboard
    steps:
    - powershell: |
        . "C:\ProgramData\Jenkins\.jenkins\workspace\GreenCodeScanPipeline\upload_to_sharepoint.ps1"
      displayName: 'Update SharePoint'