version: '3.8'

services:
  script-runner:
    build: .
    volumes:
      - ${SOURCE_DIRECTORY}:/app/source:rw
      - ${GREEN_REFINED_DIRECTORY}:/app/Green_Refined_Files:rw
    environment:
      - SOURCE_DIRECTORY=/app/source
      - GREEN_REFINED_DIRECTORY=/app/Green_Refined_Files
    env_file:
      - /app/.env
    entrypoint: ["sh", "-c", "python /app/Server_emissions_tracking.py && python /app/GreenCodeRefiner.py && python /app/Dynamic_Code_Analysis.py && python /app/Compare_emissions.py && powershell -File /app/Upload_to_SharePoint.ps1"]
