name: GreenCodeScan

on:
  push:
    branches:
      - master

jobs:
  copilot_suggest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Copilot suggest
        run: gh copilot suggest --prompts-file=C:\Code\GreenCodeApi\prompts.csv --output-dir=C:\Users\sansk\OneDrive\Desktop\StaticCodeAnalysis\destination_folder
