name: GreenCodeScan

on:
  push:
    branches:
      - master
  workflow_dispatch: # Add this trigger
    inputs: # Add inputs if required
      ref:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main' # Default branch if not specified

jobs:
  copilot_suggest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          wget https://github.com/cli/cli/releases/download/v2.44.1/gh_2.44.1_linux_amd64.tar.gz
          tar xvf gh_2.44.1_linux_amd64.tar.gz
          sudo mv gh_2.44.1_linux_amd64/bin/gh /usr/local/bin/

      - name: Run Copilot suggest
        run: |
          mkdir -p "/tmp/destination_folder"
          gh copilot suggest --prompts-file="../Code/GreenCodeApi/prompts.csv" --output-dir="/tmp/destination_folder"
