
name: Green Code Scan Pipeline

on: [push]

jobs:
  clone-repository:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  track-server-emissions:
    needs: clone-repository
    runs-on: windows-latest
    steps:
      - name: Track Server Emissions
        run: |
          $env:PATH = "C:\Users\sansk\Downloads\apache-maven-3.9.6\bin;$env:PATH"
          python server_emissions.py
        shell: powershell
        working-directory: ${{ github.workspace }}

  green-code-refiner:
    needs: track-server-emissions
    runs-on: windows-latest
    steps:
      - name: Green Code Refiner
        run: |
          $result = ''
          do {
            $result = python GreenCodeRefiner.py
            if ($result -contains 'Script-Has-Uploaded-All-Files') {
              break
            } elseif ($result -contains 'Script-Has-Remain-Some-Files-To-Uploaded') {
              Write-Output "Rerunning GreenCodeRefiner.py due to pending tasks..."
            } else {
              throw "Unexpected result from GreenCodeRefiner.py: $result"
            }
          } while ($true)
        shell: powershell
        working-directory: ${{ github.workspace }}

  dynamic-code-analysis-before:
    needs: green-code-refiner
    runs-on: windows-latest
    steps:
      - name: Dynamic Code Analysis - Before
        run: python track_emissions.py
        shell: powershell
        working-directory: ${{ github.workspace }}/tests2

  dynamic-code-analysis-after:
    needs: dynamic-code-analysis-before
    runs-on: windows-latest
    steps:
      - name: Dynamic Code Analysis - After
        run: python track_emissions_after.py
        shell: powershell
        working-directory: ${{ github.workspace }}/Refined Files

  compare-emission:
    needs: dynamic-code-analysis-after
    runs-on: windows-latest
    steps:
      - name: Compare Emission
        run: python compare_emissions.py
        shell: powershell
        working-directory: ${{ github.workspace }}

  update-dashboard:
    needs: compare-emission
    runs-on: windows-latest
    steps:
      - name: Update Dashboard
        run: |
          # PowerShell script for uploading files to SharePoint
          # Note: This script needs to be adjusted for GitHub Actions environment
          # and might require additional steps for authentication and setup.
        shell: powershell
